### PR TITLE
Update ssh2 requirement and add .gitignore

### PR DESCRIPTION
**Pull request by kimocoder**
* Support python3.12 and up
* Add .gitignore

### CODE REVIEW

**Comment by alanskiy** [comment]
Checked with python 3.12 on a mac, works.
@kimocoder , maybe add these files and directories to .gitignore too?

config.txt
data/
tmp/
full_info.txt
outdir/

**Comment by dima424658** [comment]
I've also checked on macOS and Linux with BE7000. everything seems ok, thx

**Comment by remittor** [comment]
@kimocoder 
This fork `ssh2` support only latest python versions:
https://github.com/JacobCallahan/ssh2-python/blob/8076d6996eaee389d765841ee4b0023b2291a821/setup.py#L110-L114

But I also need support for version 3.8 (for Win7).

You should probably add conditions to `requirements.txt`

**Comment by remittor** [comment]
Fixed: https://github.com/openwrt-xiaomi/xmir-patcher/commit/606763aa2a0a2c84c9d828aca2cc22dd0255841d

**Pull request closed without merging**
